baseURL = "/"
languageCode = "en-us"
title = "Rio"
theme = "hugo_theme_pickles"

[params]
  paginate = 10
  # Social accounts. Link to these accounts are displayed in the header and
  # footer
  twitter = ""
  facebook = ""
  instagram = ""
  googleplus = "" # https://plus.google.com/u/0/xxxxxx
  github = ""
  gitlab = ""
  npm = ""
  codepen = ""
  dribbble = ""
  fivehundredpx = "" # 500px
  flickr = ""
  pinterest = ""
  tumblr = ""
  vimeo = ""
  youtube = ""
  linkedin = ""
  # Disqus shortname
  disqus = ""
  # Google Analytics API key.
  ga_api_key = "Google Analytics tracking id"
  author = ""
  authorwebsite = ""
  avatar = ""
  contact = ""
  bio = ""
  
  # Short subtitle/tagline. This is displayed in the header.
  subtitle = ""
  # Logo image. This is displayed ogp image.
  logo = "images/rio-logo.svg"
  favicon = "/images/favicon.png"

[[menu.main]]
    name = "Documentation"
    url = "/docs"
    weight = 1

[[menu.main]]
    #parent = "docs"
    #name = "single"
    #url = "/docs/single"
    #weight = 1

[[menu.main]]
    #parent = "docs"
    #name = "single2"
    #url = "/docs/single2"
    #weight = 2

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 2


sectionPagesMenu = "sidemenu"

[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 30
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2017"
