baseURL = "/"
languageCode = "en-us"
title = "Rio"
theme = "hugo_theme_pickles"

[params]
  paginate = 10

  # Short subtitle/tagline. This is displayed in the header.
  subtitle = ""

  # Logo image. This is displayed ogp image.
  logo = "images/rio-logo.svg"
  favicon = "/images/favicon.png"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

    [[menu.main]]
    name = "Documentation"
    url = "/docs"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 3


sectionPagesMenu = "sidemenu"

[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = true

  # Will lower case keywords in both queries and in the indexes.
  toLower = true

  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 30
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2017"
